# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a7d8a52f06c6d8437f0efbbdca373f4c62ac544c7d5c16534b61099995b595050e1388dd07ef09d61c689efa23d819b526032783956492e28a5dcbb51086ed0

test:
  secret_key_base: a8c506f47eeca7431a65a3bfc5e1e3a2776962228c0f5001fd2fa7de7d05cf62cb91cbd80c4c8fbba58cf4848e546c572c2de6204ea682fb7f5feb9892520488

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
